export interface Product {
  id: string;
  name: string;
  price: number;
  unit: string;
  imageUrl: string;
  category: string;
  rating?: number;
  tags?: string[];
  isOrganic?: boolean;
  originalPrice?: number;
  brand?: string;
  dietary?: "Gluten Free" | "Vegan" | "Senza Lattosio" | "Bio";
  stock?: number;
  sku?: string;
  origin?: string;
  description?: string;
  ingredients?: string;
  nutrition?: {
    calories: string;
    fat: string;
    carbs: string;
    protein: string;
    sodium: string;
  };
}

export interface Category {
  id: string;
  name: string;
  imageUrl: string;
  itemCount: number;
  subcategories: string[];
}

export const CATEGORIES: Category[] = [
  {
    id: "dispensa",
    name: "La Dispensa",
    imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=400&auto=format&fit=crop",
    itemCount: 42,
    subcategories: ["Olio e Aceto", "Pasta e Riso", "Sughi e Conserve", "Spezie", "Caffè e Tè"],
  },
  {
    id: "latticini & salumi",
    name: "Latticini & Salumi",
    imageUrl: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?q=80&w=400&auto=format&fit=crop",
    itemCount: 28,
    subcategories: ["Formaggi DOP Stagionati", "Mozzarelle", "Salumi Affettati", "Burro e Panna"],
  },
  {
    id: "panetteria",
    name: "Panetteria Fresca",
    imageUrl: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?q=80&w=400&auto=format&fit=crop",
    itemCount: 14,
    subcategories: ["Pane Caldo", "Focacce", "Grissini Artigianali", "Dolci da Colazione"],
  },
  {
    id: "enoteca",
    name: "Enoteca",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=400&auto=format&fit=crop",
    itemCount: 36,
    subcategories: ["Vini Rossi DOCG", "Vini Bianchi", "Bollicine Italiane", "Liquori e Amari"],
  },
  {
    id: "frutta & verdura",
    name: "Frutta & Verdura",
    imageUrl: "https://images.unsplash.com/photo-1590502593747-42a996133562?q=80&w=400&auto=format&fit=crop",
    itemCount: 22,
    subcategories: ["Biologica Fresca", "In Stagione", "Insalate Pronte", "Frutta Secca"],
  },
  {
    id: "casa & persona",
    name: "Cura Casa & Persona",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=400&auto=format&fit=crop",
    itemCount: 19,
    subcategories: ["Detersivi Eco", "Saponi Bio", "Accessori Casa"],
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Olio Extra Vergine di Oliva Monocultivar Coratina",
    price: 18.90,
    unit: "Bottiglia 500ml",
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=600&auto=format&fit=crop",
    category: "Dispensa",
    rating: 4.9,
    tags: ["D.O.P.", "Estratto a Freddo"],
    isOrganic: true,
    brand: "Antico Frantoio",
    dietary: "Bio",
    stock: 24,
    sku: "OL-COR-500",
    origin: "Puglia, Italia",
    description: "Un olio extravergine dal carattere deciso, fruttato intenso con note tipiche di carciofo ed erba falciata. Ottenuto esclusivamente da olive Coratina selezionate.",
    ingredients: "100% Olio Extra Vergine di Oliva monocultivar Coratina.",
    nutrition: { calories: "824 kcal", fat: "91.6g", carbs: "0g", protein: "0g", sodium: "0mg" },
  },
  {
    id: "2",
    name: "Pasta Artigianale Paccheri di Gragnano I.G.P.",
    price: 3.90,
    unit: "Sacchetto 500g",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?q=80&w=600&auto=format&fit=crop",
    category: "Dispensa",
    rating: 4.8,
    tags: ["Trafilata a Bronzo"],
    isOrganic: false,
    brand: "Pastificio Liguori",
    dietary: "Gluten Free",
    stock: 120,
    sku: "PA-PAC-500",
    origin: "Campania, Italia",
    description: "Paccheri di semola di grano duro trafilati al bronzo ed essiccati lentamente a bassa temperatura per conservare intatto il sapore naturale del grano e garantire un'ottima consistenza alla cottura.",
    ingredients: "Semola di grano duro, acqua.",
    nutrition: { calories: "354 kcal", fat: "1.3g", carbs: "73.0g", protein: "12.5g", sodium: "2mg" },
  },
  {
    id: "3",
    name: "Parmigiano Reggiano DOP Vacche Rosse",
    price: 16.50,
    unit: "Trancio 250g",
    imageUrl: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?q=80&w=600&auto=format&fit=crop",
    category: "Latticini & Salumi",
    rating: 5.0,
    tags: ["D.O.P.", "Vacche Rosse"],
    isOrganic: false,
    originalPrice: 19.90,
    brand: "Consorzio Parmigiano",
    dietary: "Senza Lattosio",
    stock: 45,
    sku: "CH-PAR-250",
    origin: "Emilia-Romagna, Italia",
    description: "Parmigiano Reggiano prodotto esclusivamente con latte di Vacche Rosse della razza Reggiana. Straordinaria digeribilità, sapore dolce e profondo, ricco di sentori erbacei.",
    ingredients: "Latte, sale, caglio.",
    nutrition: { calories: "402 kcal", fat: "30.0g", carbs: "0g", protein: "32.0g", sodium: "650mg" },
  },
  {
    id: "4",
    name: "Prosciutto di Parma DOP Stagionato 24 Mesi",
    price: 11.80,
    unit: "Vaschetta 100g",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop",
    category: "Latticini & Salumi",
    rating: 4.9,
    tags: ["D.O.P.", "Invecchiato"],
    isOrganic: false,
    brand: "Salumificio Devodier",
    stock: 35,
    sku: "MT-PRM-100",
    origin: "Emilia-Romagna, Italia",
    description: "Cura artigianale di 24 mesi nelle storiche cantine di stagionatura del parmense. Fette sottili dolcissime che si sciolgono letteralmente in bocca.",
    ingredients: "Coscia di suino, sale.",
    nutrition: { calories: "269 kcal", fat: "18.3g", carbs: "0.2g", protein: "25.9g", sodium: "1.8g" },
  },
  {
    id: "5",
    name: "Crema di Pistacchio di Bronte DOP",
    price: 8.90,
    unit: "Vasetto 190g",
    imageUrl: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?q=80&w=600&auto=format&fit=crop",
    category: "Dispensa",
    rating: 4.7,
    isOrganic: true,
    brand: "Bronte Dolci",
    dietary: "Bio",
    stock: 60,
    sku: "VG-PST-190",
    origin: "Sicilia, Italia",
    description: "Crema spalmabile preparata con il pregiato Pistacchio Verde di Bronte DOP raccolto sulle pendici vulcaniche dell'Etna. Sapore intenso e vellutato.",
    ingredients: "Pistacchio Verde di Bronte DOP (45%), zucchero, olio vegetale, latte in polvere.",
    nutrition: { calories: "582 kcal", fat: "38.5g", carbs: "44.0g", protein: "8.2g", sodium: "120mg" },
  },
  {
    id: "6",
    name: "Chianti Classico Riserva DOCG",
    price: 26.00,
    unit: "Bottiglia 750ml",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=600&auto=format&fit=crop",
    category: "Enoteca",
    rating: 4.9,
    tags: ["D.O.C.G.", "Riserva"],
    isOrganic: false,
    originalPrice: 29.50,
    brand: "Castello di Brolio",
    stock: 18,
    sku: "WN-CHI-750",
    origin: "Toscana, Italia",
    description: "Vino rosso rubino intenso con profumi complessi di frutti rossi maturi, viola e accenni di vaniglia. Perfetto in abbinamento a carni rosse strutturate e formaggi stagionati.",
    ingredients: "Uve Sangiovese (min 80%), Canaiolo. Contiene solfiti.",
    nutrition: { calories: "85 kcal / 100ml", fat: "0g", carbs: "0.1g", protein: "0g", sodium: "0mg" },
  },
  {
    id: "7",
    name: "Aceto Balsamico di Modena IGP Invecchiato",
    price: 14.50,
    unit: "Bottiglia 250ml",
    imageUrl: "https://images.unsplash.com/photo-1471193945509-9ad0617afabf?q=80&w=600&auto=format&fit=crop",
    category: "Dispensa",
    rating: 4.8,
    tags: ["I.G.P.", "Invecchiato"],
    isOrganic: true,
    brand: "Acetaia Reale",
    dietary: "Bio",
    stock: 15,
    sku: "OL-BAL-250",
    origin: "Emilia-Romagna, Italia",
    description: "Invecchiato pazientemente in botti di legni pregiati (rovere, castagno, ciliegio). Densità sciropposa ed un perfetto equilibrio agrodolce.",
    ingredients: "Mosto d'uva cotto, aceto di vino. Contiene solfiti naturali.",
    nutrition: { calories: "304 kcal", fat: "0g", carbs: "70.0g", protein: "1.0g", sodium: "15mg" },
  },
  {
    id: "8",
    name: "Agrumi di Sicilia Biologici IGP",
    price: 3.90,
    unit: "Confezione 1.5kg",
    imageUrl: "https://images.unsplash.com/photo-1590502593747-42a996133562?q=80&w=600&auto=format&fit=crop",
    category: "Frutta & Verdura",
    rating: 4.6,
    isOrganic: true,
    brand: "Campania Frutta",
    dietary: "Bio",
    stock: 50,
    sku: "VG-LEM-15KG",
    origin: "Sicilia, Italia",
    description: "Raccolti freschi nelle storiche limonaie siciliane. Buccia edibile ricca di oli essenziali, perfetti sia al naturale che spremuti.",
    ingredients: "Limoni ed arance biologiche siciliane.",
    nutrition: { calories: "29 kcal", fat: "0.3g", carbs: "9.3g", protein: "1.1g", sodium: "2mg" },
  },
  {
    id: "9",
    name: "Tartufo Bianco Pregiato d'Alba",
    price: 48.00,
    unit: "Pezzo Singolo 30g",
    imageUrl: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?q=80&w=600&auto=format&fit=crop",
    category: "Dispensa",
    rating: 5.0,
    tags: ["Rarità d'Alba", "Fresco"],
    isOrganic: false,
    brand: "Tartufi Morra",
    stock: 8,
    sku: "TR-WHT-30",
    origin: "Piemonte, Italia",
    description: "Il re dei boschi piemontesi. Profumo straordinariamente complesso con note di miele, aglio e terra. Selezionato a mano e spedito in imballi termoisolati.",
    ingredients: "Tartufo Bianco Pregiato d'Alba (Tuber magnatum Pico) intero fresco.",
    nutrition: { calories: "31 kcal", fat: "0.5g", carbs: "2.5g", protein: "4.0g", sodium: "5mg" },
  },
  {
    id: "10",
    name: "Passata di Pomodoro San Marzano DOP",
    price: 2.90,
    unit: "Bottiglia 680g",
    imageUrl: "https://images.unsplash.com/photo-1595855759920-86582396756a?q=80&w=600&auto=format&fit=crop",
    category: "Dispensa",
    rating: 4.9,
    tags: ["D.O.P."],
    isOrganic: true,
    brand: "Solania",
    dietary: "Bio",
    stock: 90,
    sku: "OL-SAN-680",
    origin: "Campania, Italia",
    description: "Passata di pomodoro preparata solo con pomodori San Marzano DOP dell'agro Sarnese-Nocerino. Consistenza densa ed un sapore agrodolce equilibrato perfetto per ogni sugo.",
    ingredients: "Pomodori San Marzano DOP, sale.",
    nutrition: { calories: "22 kcal / 100g", fat: "0.1g", carbs: "4.0g", protein: "1.2g", sodium: "10mg" },
  },
  {
    id: "11",
    name: "Mozzarella di Bufala Campana DOP",
    price: 5.90,
    unit: "Pezzo 250g",
    imageUrl: "https://images.unsplash.com/photo-1559561853-08451507cbe7?q=80&w=600&auto=format&fit=crop",
    category: "Latticini & Salumi",
    rating: 4.9,
    tags: ["D.O.P.", "Fresco"],
    isOrganic: false,
    brand: "La Cilentana",
    stock: 25,
    sku: "CH-BUF-250",
    origin: "Campania, Italia",
    description: "Mozzarella di Bufala DOP prodotta artigianalmente. Esterno porcellanato brillante ed un cuore morbido e succoso ricco di latte, lavorata tradizionalmente a mano.",
    ingredients: "Latte di bufala, sieroinnesto naturale, sale, caglio.",
    nutrition: { calories: "288 kcal", fat: "24.4g", carbs: "0.7g", protein: "16.7g", sodium: "200mg" },
  },
  {
    id: "12",
    name: "Franciacorta Brut DOCG Millesimato",
    price: 32.00,
    unit: "Bottiglia 750ml",
    imageUrl: "https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb?q=80&w=600&auto=format&fit=crop",
    category: "Enoteca",
    rating: 5.0,
    tags: ["D.O.C.G.", "Metodo Classico"],
    isOrganic: false,
    brand: "Bellavista",
    stock: 12,
    sku: "WN-FRA-750",
    origin: "Lombardia, Italia",
    description: "Prestigioso Franciacorta spumante dal perlage finissimo ed elegante. Note di crosta di pane, lievito e agrumi canditi. Eccellente per aperitivi di lusso ed antipasti di pesce.",
    ingredients: "Uve Chardonnay, Pinot Nero. Contiene solfiti.",
    nutrition: { calories: "82 kcal / 100ml", fat: "0g", carbs: "0.2g", protein: "0g", sodium: "0mg" },
  },
];
